# Generated by Django 4.1.7 on 2024-04-21 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jobs.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('company', models.CharField(max_length=200)),
                ('sallery', models.IntegerField()),
                ('type', models.CharField(choices=[('FL', 'FULL TIME'), ('PT', 'PART TIME')], default='FL', max_length=3)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(default=jobs.models.get_default_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
