# Generated by Django 4.1.7 on 2024-04-21 13:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('company', models.CharField(max_length=200)),
                ('sallery', models.IntegerField()),
                ('type', models.CharField(choices=[('FL', 'FULL TIME'), ('PT', 'PART TIME')], default='FL', max_length=3)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
