# Generated by Django 4.1.7 on 2024-04-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='type',
            field=models.CharField(choices=[('PT', 'PART TIME'), ('FL', 'FULL TIME')], default='FL', max_length=3),
        ),
    ]
