# Generated by Django 4.1.7 on 2024-04-21 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_jobs_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='type',
            field=models.CharField(choices=[('FL', 'FULL TIME'), ('PT', 'PART TIME')], default='FL', max_length=3),
        ),
    ]
